"""Initial migration

Revision ID: fbccc20ee6e8
Revises: 
Create Date: 2024-12-23 17:48:55.493469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbccc20ee6e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NOTIFICATIONS')
    op.drop_table('DIGITAL_ACCESS')
    op.drop_table('BORROWED_BOOKS')
    with op.batch_alter_table('LIBRARIANS', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    op.drop_table('LIBRARIANS')
    op.drop_table('SYSTEM_POLICIES')
    with op.batch_alter_table('MEMBERS', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    op.drop_table('MEMBERS')
    op.drop_table('MEMBER_TIERS')
    op.drop_table('MEMBERSHIP_TIERS')
    with op.batch_alter_table('ADMINS', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    op.drop_table('ADMINS')
    with op.batch_alter_table('BOOKS', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('BOOK_ORDERS', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('FINES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('fines_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('fines_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'BORROW_TRANSACTIONS', ['transaction_id'], ['transaction_id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('fine_rate')
        batch_op.drop_column('fine_amount')
        batch_op.drop_column('borrow_id')

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=15), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('FINES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fine_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('fine_rate', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fines_ibfk_2', 'BORROWED_BOOKS', ['borrow_id'], ['borrow_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fines_ibfk_1', 'USERS', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('paid')
        batch_op.drop_column('amount')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('BOOK_ORDERS', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('BOOKS', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.create_table('ADMINS',
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('admin_level', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='admins_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ADMINS', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('MEMBERSHIP_TIERS',
    sa.Column('tier_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tier_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('borrowing_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fine_discount', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.PrimaryKeyConstraint('tier_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('MEMBER_TIERS',
    sa.Column('member_tier_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['MEMBERS.member_id'], name='member_tiers_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['MEMBERSHIP_TIERS.tier_id'], name='member_tiers_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_tier_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('MEMBERS',
    sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('membership_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('active', 'inactive'), server_default=sa.text("'active'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='members_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('MEMBERS', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('SYSTEM_POLICIES',
    sa.Column('policy_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('policy_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('policy_value', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('LIBRARIANS',
    sa.Column('librarian_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='librarians_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('librarian_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('LIBRARIANS', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('BORROWED_BOOKS',
    sa.Column('borrow_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('borrow_date', sa.DATE(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('fine_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOKS.book_id'], name='borrowed_books_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='borrowed_books_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('borrow_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('DIGITAL_ACCESS',
    sa.Column('digital_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('eBook_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('access_date', sa.DATE(), nullable=False),
    sa.Column('backup_status', mysql.ENUM('pending', 'completed'), server_default=sa.text("'pending'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='digital_access_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('digital_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('NOTIFICATIONS',
    sa.Column('notification_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('email', 'sms'), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('sent_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.user_id'], name='notifications_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
